Added validations and SelectInput
droopy-frba/app pull request #20
Opened 2022-08-03 00:39 UTC by guidoRosito1107

2022-08-03 00:50 UTC, leoguerberg requested changes

2022-08-03 00:50 UTC, leoguerberg commented on src/assets/theme/light.ts
> +    RED: '#FF0000',
@guidoRosito1107 para que se usa este color? Se le podria buscar un nombre mas generico tipo ERROR o el uso que sea?

2022-08-03 00:50 UTC, leoguerberg commented on src/components/Inputs/Select/index.tsx
> +          fontFamily: lightTheme.FONTS.REGULAR,
@guidoRosito1107 si todos estos estilos no se pueden mover a un styled component, en vez de importar directo el `lightTheme`, sacalo usando el hook `useTheme`, por si a futuro hacemos el darkMode

2022-08-03 00:50 UTC, leoguerberg commented on src/components/Inputs/Select/index.tsx
> +  onChangeFormik,
@guidoRosito1107 diria ponerle `onChange` a esto, al input no le deberia importar si se usa formik o no

2022-08-03 00:50 UTC, leoguerberg commented on src/components/Inputs/Select/index.tsx
> +        onChangeValue={onChangeFormik()}
@guidoRosito1107 medio raro esto, seguro que no deberia ser `onChangeValue={onChangeFormik}`?

2022-08-03 00:50 UTC, leoguerberg commented on src/components/Inputs/Select/index.tsx
> +  const [value, setValue] = useState<any>();
@guidoRosito1107 sugiero que esto se lo pasemos de afuera como prop en vez de tenerlo como state en el componente

2022-08-03 00:50 UTC, leoguerberg commented on src/components/Inputs/Select/types.ts
> +  onChangeFormik: any;
@guidoRosito1107 esto se deberia poder tipar, calculo como `(value: string) => void`

2022-08-03 00:50 UTC, leoguerberg commented on src/components/Inputs/TextInput/types.ts
> +  errorMessage?: string;
@guidoRosito1107 no podriamos dejar solo la prop de `errorMessage` en vez de tener dos?

2022-08-03 00:50 UTC, leoguerberg commented on src/screens/Signup/SignupUserData/index.tsx
> +                    placeholderTextColor={lightTheme.COLORS.NEUTRAL_200}
@guidoRosito1107 mismo aca, usemos `useTheme`. Y pregunta, para que necesitamos pasarle como prop el color del placeholder? en que casos cambiaria?

2022-08-03 00:52 UTC, guidoRosito1107 commented on src/assets/theme/light.ts
> +    RED: '#FF0000',
Si obvio! No lo quise categorizar únicamente para errores porque también lo vamos a estar usando por ejemplo en las búsquedas live.

2022-08-03 00:54 UTC, guidoRosito1107 commented on src/screens/Signup/SignupUserData/index.tsx
> +                    placeholderTextColor={lightTheme.COLORS.NEUTRAL_200}
Esto lo hice nada más para darle flexibilidad. No sabemos si lo vamos a tener que cambiar y como TextInput es un componente genérico me parecía copado que podamos asignarle el color que querramos.

2022-08-03 02:38 UTC, guidoRosito1107 commented on src/components/Inputs/Select/index.tsx
> +          fontFamily: lightTheme.FONTS.REGULAR,
Fixed.

2022-08-03 02:38 UTC, guidoRosito1107 commented on src/components/Inputs/Select/index.tsx
> +  onChangeFormik,
Fixed

2022-08-03 02:51 UTC, guidoRosito1107 commented on src/components/Inputs/Select/index.tsx
> +        onChangeValue={onChangeFormik()}
fixed

2022-08-03 02:52 UTC, guidoRosito1107 commented on src/components/Inputs/Select/index.tsx
> +  const [value, setValue] = useState<any>();
Talvez estoy de acuerdo con el value. Pero no con el open. Me parece más cómodo que el tenga conocimiento de su propio estado si está abierto o no.

2022-08-03 02:53 UTC, guidoRosito1107 commented on src/components/Inputs/Select/types.ts
> +  onChangeFormik: any;
Por algún motivo TS se enoja si lo pongo así.

2022-08-03 03:21 UTC, guidoRosito1107 commented on src/components/Inputs/TextInput/types.ts
> +  errorMessage?: string;
fixed

2022-08-04 00:50 UTC, leoguerberg commented on src/components/Inputs/Select/index.tsx
> +  const [value, setValue] = useState<any>();
@guidoRosito1107 sisi perfecto, decia el value nomas :+1:

2022-08-04 00:51 UTC, leoguerberg commented on src/components/Inputs/Select/types.ts
> +  onChangeFormik: any;
@guidoRosito1107 TS se la come

2022-08-04 00:52 UTC, leoguerberg approved these changes

2022-08-04 00:52 UTC, merged